/*
* generated by Xtext
*/
package edu.cmu.sei.alisa.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import edu.cmu.sei.alisa.services.AlisaGrammarAccess;

public class AlisaParser extends AbstractContentAssistParser {
	
	@Inject
	private AlisaGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected edu.cmu.sei.alisa.ui.contentassist.antlr.internal.InternalAlisaParser createParser() {
		edu.cmu.sei.alisa.ui.contentassist.antlr.internal.InternalAlisaParser result = new edu.cmu.sei.alisa.ui.contentassist.antlr.internal.InternalAlisaParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getAlisaModelAccess().getContentAlternatives_0(), "rule__AlisaModel__ContentAlternatives_0");
					put(grammarAccess.getRequirementDecompositionAccess().getAlternatives(), "rule__RequirementDecomposition__Alternatives");
					put(grammarAccess.getRequirementDecompositionAccess().getTypeAlternatives_1_1_0(), "rule__RequirementDecomposition__TypeAlternatives_1_1_0");
					put(grammarAccess.getVerificationMethodAccess().getAlternatives(), "rule__VerificationMethod__Alternatives");
					put(grammarAccess.getVerificationResultStateAccess().getAlternatives_2(), "rule__VerificationResultState__Alternatives_2");
					put(grammarAccess.getVerificationResultStatusAccess().getAlternatives_2(), "rule__VerificationResultStatus__Alternatives_2");
					put(grammarAccess.getStakeholderAccess().getGroup(), "rule__Stakeholder__Group__0");
					put(grammarAccess.getStakeholderAccess().getGroup_2(), "rule__Stakeholder__Group_2__0");
					put(grammarAccess.getStakeholderAccess().getGroup_3(), "rule__Stakeholder__Group_3__0");
					put(grammarAccess.getStakeholderAccess().getGroup_4(), "rule__Stakeholder__Group_4__0");
					put(grammarAccess.getRequirementAccess().getGroup(), "rule__Requirement__Group__0");
					put(grammarAccess.getRequirementAccess().getGroup_2(), "rule__Requirement__Group_2__0");
					put(grammarAccess.getRequirementAccess().getGroup_3(), "rule__Requirement__Group_3__0");
					put(grammarAccess.getRequirementAccess().getGroup_4(), "rule__Requirement__Group_4__0");
					put(grammarAccess.getRequirementAccess().getGroup_5(), "rule__Requirement__Group_5__0");
					put(grammarAccess.getRequirementAccess().getGroup_6(), "rule__Requirement__Group_6__0");
					put(grammarAccess.getRequirementDecompositionAccess().getGroup_1(), "rule__RequirementDecomposition__Group_1__0");
					put(grammarAccess.getElementTypeAccess().getGroup(), "rule__ElementType__Group__0");
					put(grammarAccess.getElementTypeAccess().getGroup_3(), "rule__ElementType__Group_3__0");
					put(grammarAccess.getElementTypeAccess().getGroup_4(), "rule__ElementType__Group_4__0");
					put(grammarAccess.getElementTypeAccess().getGroup_5(), "rule__ElementType__Group_5__0");
					put(grammarAccess.getElementTypeAccess().getGroup_6(), "rule__ElementType__Group_6__0");
					put(grammarAccess.getElementTypeAccess().getGroup_7(), "rule__ElementType__Group_7__0");
					put(grammarAccess.getVerificationActivityAccess().getGroup(), "rule__VerificationActivity__Group__0");
					put(grammarAccess.getVerificationActivityAccess().getGroup_3(), "rule__VerificationActivity__Group_3__0");
					put(grammarAccess.getVerificationActivityAccess().getGroup_4(), "rule__VerificationActivity__Group_4__0");
					put(grammarAccess.getVerificationActivityAccess().getGroup_5(), "rule__VerificationActivity__Group_5__0");
					put(grammarAccess.getVerificationResultAccess().getGroup(), "rule__VerificationResult__Group__0");
					put(grammarAccess.getVerificationResultAccess().getGroup_5(), "rule__VerificationResult__Group_5__0");
					put(grammarAccess.getVerificationResultAccess().getGroup_6(), "rule__VerificationResult__Group_6__0");
					put(grammarAccess.getVerificationResultAccess().getGroup_7(), "rule__VerificationResult__Group_7__0");
					put(grammarAccess.getVerificationResultAccess().getGroup_8(), "rule__VerificationResult__Group_8__0");
					put(grammarAccess.getVerificationResultAccess().getGroup_9(), "rule__VerificationResult__Group_9__0");
					put(grammarAccess.getVerificationResultStateAccess().getGroup(), "rule__VerificationResultState__Group__0");
					put(grammarAccess.getVerificationResultStatusAccess().getGroup(), "rule__VerificationResultStatus__Group__0");
					put(grammarAccess.getAlisaModelAccess().getContentAssignment(), "rule__AlisaModel__ContentAssignment");
					put(grammarAccess.getStakeholderAccess().getNameAssignment_1(), "rule__Stakeholder__NameAssignment_1");
					put(grammarAccess.getStakeholderAccess().getTitleAssignment_2_2(), "rule__Stakeholder__TitleAssignment_2_2");
					put(grammarAccess.getStakeholderAccess().getDescriptionAssignment_3_2(), "rule__Stakeholder__DescriptionAssignment_3_2");
					put(grammarAccess.getStakeholderAccess().getRoleAssignment_4_2(), "rule__Stakeholder__RoleAssignment_4_2");
					put(grammarAccess.getRequirementAccess().getNameAssignment_1(), "rule__Requirement__NameAssignment_1");
					put(grammarAccess.getRequirementAccess().getTitleAssignment_2_2(), "rule__Requirement__TitleAssignment_2_2");
					put(grammarAccess.getRequirementAccess().getDescriptionAssignment_3_2(), "rule__Requirement__DescriptionAssignment_3_2");
					put(grammarAccess.getRequirementAccess().getCommentAssignment_4_2(), "rule__Requirement__CommentAssignment_4_2");
					put(grammarAccess.getRequirementAccess().getReferencedByAssignment_5_3(), "rule__Requirement__ReferencedByAssignment_5_3");
					put(grammarAccess.getRequirementAccess().getDecomposedByAssignment_6_3(), "rule__Requirement__DecomposedByAssignment_6_3");
					put(grammarAccess.getRequirementDecompositionAccess().getElementsAssignment_0(), "rule__RequirementDecomposition__ElementsAssignment_0");
					put(grammarAccess.getRequirementDecompositionAccess().getLeftAssignment_1_0(), "rule__RequirementDecomposition__LeftAssignment_1_0");
					put(grammarAccess.getRequirementDecompositionAccess().getTypeAssignment_1_1(), "rule__RequirementDecomposition__TypeAssignment_1_1");
					put(grammarAccess.getRequirementDecompositionAccess().getRightAssignment_1_2(), "rule__RequirementDecomposition__RightAssignment_1_2");
					put(grammarAccess.getElementTypeAccess().getNameAssignment_2(), "rule__ElementType__NameAssignment_2");
					put(grammarAccess.getElementTypeAccess().getReferenceAssignment_3_2(), "rule__ElementType__ReferenceAssignment_3_2");
					put(grammarAccess.getElementTypeAccess().getElementTypeAssignment_4_2(), "rule__ElementType__ElementTypeAssignment_4_2");
					put(grammarAccess.getElementTypeAccess().getModelTypeAssignment_5_2(), "rule__ElementType__ModelTypeAssignment_5_2");
					put(grammarAccess.getElementTypeAccess().getDetailsAssignment_6_2(), "rule__ElementType__DetailsAssignment_6_2");
					put(grammarAccess.getElementTypeAccess().getVersionAssignment_7_2(), "rule__ElementType__VersionAssignment_7_2");
					put(grammarAccess.getVerificationActivityAccess().getNameAssignment_2(), "rule__VerificationActivity__NameAssignment_2");
					put(grammarAccess.getVerificationActivityAccess().getTitleAssignment_3_2(), "rule__VerificationActivity__TitleAssignment_3_2");
					put(grammarAccess.getVerificationActivityAccess().getDescriptionAssignment_4_2(), "rule__VerificationActivity__DescriptionAssignment_4_2");
					put(grammarAccess.getVerificationActivityAccess().getMethodAssignment_5_2(), "rule__VerificationActivity__MethodAssignment_5_2");
					put(grammarAccess.getVerificationResultAccess().getNameAssignment_2(), "rule__VerificationResult__NameAssignment_2");
					put(grammarAccess.getVerificationResultAccess().getReferencedVerificationMethodAssignment_4(), "rule__VerificationResult__ReferencedVerificationMethodAssignment_4");
					put(grammarAccess.getVerificationResultAccess().getTitleAssignment_5_2(), "rule__VerificationResult__TitleAssignment_5_2");
					put(grammarAccess.getVerificationResultAccess().getDescriptionAssignment_6_2(), "rule__VerificationResult__DescriptionAssignment_6_2");
					put(grammarAccess.getVerificationResultAccess().getMethodAssignment_7_2(), "rule__VerificationResult__MethodAssignment_7_2");
					put(grammarAccess.getVerificationResultAccess().getStateAssignment_8_2(), "rule__VerificationResult__StateAssignment_8_2");
					put(grammarAccess.getVerificationResultAccess().getStatusAssignment_9_2(), "rule__VerificationResult__StatusAssignment_9_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			edu.cmu.sei.alisa.ui.contentassist.antlr.internal.InternalAlisaParser typedParser = (edu.cmu.sei.alisa.ui.contentassist.antlr.internal.InternalAlisaParser) parser;
			typedParser.entryRuleAlisaModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AlisaGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AlisaGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
