/*
 * generated by Xtext
 */
package edu.cmu.sei.alisa.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;
// import com.google.inject.Inject;
// import edu.cmu.sei.alisa.services.AlisaGrammarAccess

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class AlisaFormatter extends AbstractDeclarativeFormatter {
		protected void configureFormatting(FormattingConfig c) {
			
		}

}
  