/*
* generated by Xtext
*/
package edu.cmu.sei.alisa.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
public class AlisaProposalProvider extends edu.cmu.sei.alisa.ui.contentassist.AbstractAlisaProposalProvider {

}
