/*
 * generated by Xtext
 */
package edu.cmu.sei.alisa.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import edu.cmu.sei.alisa.ui.internal.AlisaActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AlisaExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return AlisaActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return AlisaActivator.getInstance().getInjector(AlisaActivator.EDU_CMU_SEI_ALISA_ALISA);
	}
	
}
