/*
 * generated by Xtext
 */
package edu.cmu.sei.alisa.scoping;
import org.eclipse.xtext.scoping.impl.AbstractDeclarativeScopeProvider;
/**
 * This class contains custom scoping description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation.html#scoping
 * on how and when to use it 
 *
 */
public class AlisaScopeProvider extends AbstractDeclarativeScopeProvider {

}
    